services:
  postgres:
    image: postgres:latest
    container_name: resource-manager-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mystrongpassword
      POSTGRES_DB: resource_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
